volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: tash1gi/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: tash1gi/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: tash1gi/foodgram_gateway
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/usr/share/nginx/html/
      - media:/var/html/media/
    depends_on:
      - backend
